### PR TITLE
adds email address

### PR DESCRIPTION
**Pull request by cgerrior**

### CODE REVIEW

**Comment by jaxxrosen735** [comment]
Has my commit been merged? I can't tell....

**Comment by carlvlewis** [comment]
Yep, merged!

**Comment by carlvlewis** [comment]
Also will add you to repo so you can auto-merge commits if you want

**Comment by jaxxrosen735** [comment]
Can you email me an invite to the slack channels? I can't find the links
anywhere
Thanks.

**Comment by carlvlewis** [comment]
I was actually just about to fix the Slack invite link earlier. It broke.
Umm, I'm on mobile at present, but can I get you admin privileges in like
an hour? I'll set a reminder.

**Comment by jaxxrosen735** [comment]
perfect thanks

**Comment by carlvlewis** [comment]
No, thank you--we need to make this all clearer and send out an invite via
email. I have the emails of everyone who checked into the event but a good
bit of attendees didn't check in. I'm also waiting on Brian to send over
the teams for each contrib.

**Comment by jaxxrosen735** [comment]
Okay. I got it. Thanks for keeping me in the loop.

**Comment by carlvlewis** [comment]
@joshrosen735 -- my apologies. I was emailing responses to your questions via mobile and didn't notice that it was you who was asking about commits merging. We have no open pull requests from you at the moment on the track-a-cat repo. Is it somewhere else?

**Comment by jaxxrosen735** [comment]
No it was on the cat repo, I can run it again this morning.

**Comment by jaxxrosen735** [comment]
Did you get the pull requests for the 2 files? I tried to merge them yesterday. **@carlvlewis**

**Pull request merged**
